# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recsys_pb2 as recsys__pb2


class RecommenderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.recommend = channel.unary_unary(
        '/recsys.Recommender/recommend',
        request_serializer=recsys__pb2.RecommenderRequest.SerializeToString,
        response_deserializer=recsys__pb2.RecommenderResponse.FromString,
        )


class RecommenderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def recommend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'recommend': grpc.unary_unary_rpc_method_handler(
          servicer.recommend,
          request_deserializer=recsys__pb2.RecommenderRequest.FromString,
          response_serializer=recsys__pb2.RecommenderResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'recsys.Recommender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
